### ISSUE TITLE
Sponsoring / Partnerships

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Versity#1]
Comme je l'ai énoncé sur slack, il pourrait être intéressant de contacter quelques marques / enseignes spécialisés dans le domaine de l'informatique ou des jeux vidéos pour voir si d'éventuels partenariats ou même sponsorisation serait possible.

Je ferais une liste ici afin de voir les marques/enseignes intéressantes contacté, pouvant être contacté ou à contacter.
- Idées d'enseignes / marques / Associations :
  - Student Gaming League (En contact)

**Comment by Uinelj** [comment]
Je ne t'en ai pas encore parlé, mais j'ai un bon contact : La Student Gaming League, et des BDE de l'ESSEC qui veulent faire une Business Fair sur l'eSport. Je suis dans un groupe FB avec eux et Pierre-Elie, étant donné que pour les années précédentes je représentais Versity pour LifeUp :)

**Comment by AlexFourgs** [comment]
C'est cool ! J'ai regardé un petit peu.
J'ai trouvé ça aussi : http://www.lanpartyeh.com/host/sponsor

ça regroupe la majorité des marques qui sponsorisent des LANs avec les formulaires pour faire des demande de sponsor :)

**Comment by Uinelj** [comment]
@Eresia Je t'ai normalement mis dans la boucle à ce niveau : Tu as des news ?

**Comment by Eresia** [comment]
Pour tout dire, j'ai pas vraiment encore pris la peine de regarder
