### ISSUE TITLE
Réunion Technique 

### ISSUE THREAD

**Issue by Eresia** [bdeecho/Versity#11]
Réunion Technique avec la Vie Associative le 02/11.

Seront présent :
- La vie Assoc
- La DISI
- La DPI
- Un chef cuisinier du CROUSS

**Comment by Eresia** [comment]
Je me rend compte que j'ai jamais fait de vrai compte rendu de la réunion.

Du coups était présent deux membres de la DISI, deux membres de la vie Assoc, deux membres du CROUSS dont le cuisinier de St Martin, le chef de la sécurité, la responsable évenementielle, et moi même.

En gros, tout le monde est chaud pour la LAN. Le Crouss est ravi de devenir notre prestataire et propose un menu buffet froid parfait pour nos besoins et propose aussi de tenir un bar sans alcool pendant toute la Nuit.

Niveau réseau, la DISI a dit que c'était bon, ils avaient le temps de s'arranger.

Le gros point noir est l’électricité. La DPI n'ayant pas été mise dans la boucle, elle n'était pas présente. La DISI s'est chargé de la contacter. C'est a elle de nous dire si c'est viable de faire ça au RU, s'il peuvent emmener un truc etc.

Si ça n'est pas possible, d'autres lieux ont été évoqué. Soit le Hall des Chênes 2 qui est disponible à partir du Vendredi soir et qui nous donne accès aux amphis proches (Un très bon endroit). Environ 600m² si je me souviens bien (contre 400 au RU). Soit le Hall de Neuville, plus petit (300 m²) mais envisageable aussi. Ces lieux seront peut-être plus favorable au niveau électricité.

Renier m'a dit aussi que si on arrive à faire la LAN une fois à un endroit, ça sera beaucoup plus simple les fois d'après. Et qu'on peut même insister la dessus pour avoir de véritables installations dans le RU, qui pourra devenir un véritable endroit d’événement, et y a du potentiel (il parlait d'environ 10 000 euros donnés par la fac)

Et il m'a aussi dit que si jamais on voulait refaire des petites LAN au 5ème (des "Mini-Versity" ?), on serait les bienvenue et il peut nous installer ça en un temps record.

En bref, tout le monde a envie que ça se fasse, on attend plus que la question de l'électricité.

La date est reportée vers Février.

Je crois que j'ai tout dit, bisous

**Comment by Uinelj** [comment]
Très très bonnes nouvelles :) On se croirait dans les issues Cadence : Tout le monde est chaud mais techniquement c'est raloud. Merci des infos <3
