### ISSUE TITLE
Faire un dossier pour les sponsors

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Versity#16]
Il faudrait faire un véritable GROS dossier qui présente Versity de A à Z pour réussir à obtenir des sponsors et du coup des fonds pour des événements plus conséquents.

Voila le squelette du dossier : https://hackmd.io/GwQwnADAZhAmDGBaA7ARgCwCNHthEiI6AHBIgKwgCm5VV6qUxUIQA===

Vous êtes bien entendu tous conviés à travailler dessus si vous voulez/pouvez.

**Comment by Eresia** [comment]
Je sais pas trop ou le mettre mais je vous rappelle qu'on a une vrai vidéo de la #4 
https://www.youtube.com/watch?v=C76-BL51zag

Ou celle la peut-être un peu plus complète :
https://www.facebook.com/VersityLans/videos/528698040625432/
