### ISSUE TITLE
Boissons

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Versity#17]
* 78 Bouteilles de Coca
* 78 Bouteilles de Ice Tea
* 58 Bouteilles de Oasis Tropical
* 315L d'eau
* 35L de jus d'orange
* 35L de jus de pomme
* 1000 gobelets de 50cl
* Un comptoir
* 3 Bac à glaces 20kg
* 3 Saces de glaces de 20kg

J'attend toujours vos retours avant de demander à Barnum

**Comment by Eresia** [comment]
Ok pour moi (On garde les mêmes quantité même si on tombe à 170 personnes ?)

**Comment by AlexFourgs** [comment]
Oui tant qu'à faire :)
