### ISSUE TITLE
Décider des dates pour les deux LANs.

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Versity#2]
Bien entendu il faudra que les dates concordent avec les Boilers et qu'elles conviennent à l'ensemble du staff Versity.

**Comment by Eresia** [comment]
Si on veut en faire trois va falloir fixer la première très rapidement !

**Comment by Uinelj** [comment]
Complètement d'accord. @AlexFourgs et moi même étant à 200% sur le projet Boiler, qui demande pas mal de choses, je pense qu'on a besoin d'aide là dessus ! Proposez nous des dates :)

**Comment by Eresia** [comment]
Je dirais mi-Décembre pour la première (pour avant j'ai peur que ça soit trop limite).
Et ne pas trop la rapprocher des vacances de Noël, il y a déjà pas mal d’événements prévu par les autres assoc à ces dates

**Comment by AlexFourgs** [comment]
Ok pour mi décembre la première !

**Comment by Eresia** [comment]
Je demande une reconfirmation pour la mi-décembre car j'ai cru comprendre que la date de la première Cadence changeait. On maintient quand même ?

**Comment by AlexFourgs** [comment]
Vendredi 16 Décembre on a la première Cadence, donc pourquoi ne pas faire la LAN le vendredi d'avant ? Sinon la première semaine de la rentrée de Janvier ?

**Comment by Eresia** [comment]
On peut pour le Vendredi d'avant (jusqu'au Samedi matin c'est ça ?)
Par contre si on le fait en Janvier, je pense que dès la rentrée c'est chaud parce tout les services seront en rentrée de vacances et du coups ça sera chaud au niveau de l'orga. Mais à discuter

**Comment by Eresia** [comment]
Bon, on ouvrira une nouvelle issue quand on aura le lieu de la LAN, je ferme
