### ISSUE TITLE
Information précise sur la LAN de Décembre/Janvier pour demande de Manif

### ISSUE THREAD

**Issue by Eresia** [bdeecho/Versity#4]
Mettre ici les info concernant cette LAN (Nb de personnes, Horaires etc)

Voici la première version de la demande de Manif :
https://github.com/bdeecho/Versity/blob/master/Versity-Decembre-2016.pdf

**Comment by AlexFourgs** [comment]
La dernière LAN on avait 150 personnes non ?

Il faut prendre contact avec Life Up aussi :)

**Comment by Eresia** [comment]
Bah ouai mais le RU a une capacité de cb ?

**Comment by AlexFourgs** [comment]
En soit la capacité du RU je pense pas que ce soit le réél soucis, il faudrait qu'on sache combien de personnes on attend, et surtout adapter les horaires en fonction du nombre de personnes aussi.

**Comment by Eresia** [comment]
Bah si, c'est la capacité du RU qui nous donne le nombre de personnes attendus.

Mais on avait déjà fait le plan et tout en faite

**Comment by AlexFourgs** [comment]
Du coup pour la date on fais quoi ?

Si c'est Décembre / Janvier il faudrait qu'on fasse la demande de sub pour mi-octobre

**Comment by Eresia** [comment]
9 Décembre ?

Et j'aimerai bien avoir les budget des dernières LAN si possible

**Comment by AlexFourgs** [comment]
Je te met ça rapidement ;) 

Du coup t'a fais la demande de manifestations ?

**Comment by Eresia** [comment]
Pas encore, je m'y met rapidemment

**Comment by Eresia** [comment]
Besoin urgent de vos avis sur : 

https://github.com/bdeecho/Versity/blob/master/Versity-Decembre-2016.pdf

et

https://github.com/bdeecho/Versity/blob/master/plan_ru_mesures_journee_3.0.png

Sachant que j'ai prévus de vidéo projecteur pour des potentiels stream mais que je n'ai pas prévu de gens non joueur dans mon calcul. Je peux je pense en rajouter, faut juste me dire si c'est pertinent

**Comment by AlexFourgs** [comment]
17h - 00h ou vraiment 17h - 12h ?

Les plans sont géniaux ! Pour les non joueurs on verra, on pourra faire un coin tranquille à l'endroit ou les profs mangent entre eux, à moins qu'on s'en serve pour le côté admin de la lan pour nous.

**Comment by Eresia** [comment]
Bah je me dis quitte à se faire chiez à prendre le RU et faire ça un Vendredi soir, j'ai envie de viser gros. En plus si on fait plus court, les tournois ne pourront pas se finir.

Et pour les non joueurs c'est juste pour savoir si je rajouter genre 30 personnes de plus dans les personnes attendu (je met 250 quoi)

**Comment by Eresia** [comment]
(Et je passe la réservation à partir de 16h et l'arrivée du public à 18h30, on a besoin de marge)

**Comment by AlexFourgs** [comment]
Faut voir à quelle heure arrive les personnes.

12h le lendemain je trouve que ça fais vraiment long perso.

Un 17h - 4h/6h me semble suffisant non ?

**Comment by akkes** [comment]
À mon avis mettre en évidence les câbles pourrait être cool. c'est ce qui risque de poser problème en l'état

**Comment by Agurato** [comment]
@Eresia :
1. Y'a combien de personnes par équipe sur Overwatch (vu que tu en as mis 36) ?
2. Il faudrait voir si il y a assez de tables dans le RU

@AlexFourgs :
Je pense que le côté prof serait plus pour l'orga (c'est ce à quoi on avait pensé l'année dernière)

**Comment by AlexFourgs** [comment]
On peut faire appel à un prestataire pour de la location si nécessaire.

Faut prendre contact rapidement avec la DISI pour voir ce qui est nécessaire et ce qu'ils ont.

@Agurato Ok pas de soucis, mais comme le souligne @Eresia ce serait intéressant d'avoir un espace chill ppr oklm

**Comment by Eresia** [comment]
@akkes Je n'ai pas d'info de ou va venir l'électricité, donc je ne peux pas prévoir les cables

@Agurato il y en a 6 donc c'est normal
Pour les tables c'est dans la demande de manif

@AlexFourgs La DISI fera parti de la réunion technique normalement

**Comment by Eresia** [comment]
Du coups je balance tout ça à la vie assoc ?

**Comment by Agurato** [comment]
T'as changé la date ? Pour mettre vendredi ET samedi

**Comment by Eresia** [comment]
Bien vu, c'est fait

**Comment by Eresia** [comment]
Demande envoyée, je ferme
