### ISSUE TITLE
Salles nécessaires

### ISSUE THREAD

**Issue by Agurato** [bdeecho/Versity#7]
On en avait vite fait parler l'année dernière : est-ce qu'on demande pour avoir l'amphi E1 qui est juste à côté ? Y'a juste une porte à ouvrir avec un badge ..

**Comment by Eresia** [comment]
Bonne idée, je demanderais à la réu

**Comment by Eresia** [comment]
J'ai demandé, c'est en "pourquoi pas, faut voir pour le gardiennage".
